package com.example.autorskapravabackend.model;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.02.01 at 03:08:59 PM CET
//

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the rs.ac.uns.ftn.jaxb.example3 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    public ObjectFactory() {
    }

    public ZahtevZaAutorskaPrava createZahtevZaAutorskaPrava() {
        return new ZahtevZaAutorskaPrava();
    }

    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    public TLice createTLice() {
        return new TLice();
    }

    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    public SadrzajZahteva createSadrzajZahteva() {
        return new SadrzajZahteva();
    }

    public AutorskoDelo createAutorskoDelo() {
        return new AutorskoDelo();
    }

    public InformacijeOZahtevu createInformacijeOZahtevu() {
        return new InformacijeOZahtevu();
    }

    public OsnovniLicniPodaci createOsnovniLicniPodaci() {
        return new OsnovniLicniPodaci();
    }

    public PodnosilacZahteva createPodnosilacZahteva() {
        return new PodnosilacZahteva();
    }

    public Autor createTAutor() {
        return new Autor();
    }

    public ZasnivanoDelo createZasnivanoDelo() {
        return new ZasnivanoDelo();
    }

    public PodaciOAutoru createAutor() {
        return new PodaciOAutoru();
    }

    public Adresa createAdresa() {
        return new Adresa();
    }
}

