//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.01 at 03:08:59 PM CET 
//


package com.example.patentbackend.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the rs.ac.uns.ftn.jaxb.example3 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

//    private final static QName _OdslusanPredmet_QNAME = new QName("http://www.ftn.uns.ac.rs/patent", "odslusan_predmet");

    public ObjectFactory() {
    }

    public ZahtevZaPriznanjePatenta createZahtevZaPriznanjePatenta() {
        return new ZahtevZaPriznanjePatenta();
    }

    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    public TLice createTLice() {
        return new TLice();
    }

    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }


    public SadrzajZahtevaZaPriznanjePatenta createSadrzajZahtevaZaPriznanjePatenta() {
        return new SadrzajZahtevaZaPriznanjePatenta();
    }

    public RanijaPrijava createRanijaPrijava() {
        return new RanijaPrijava();
    }

    public PodaciOPunomocniku createPodaciOPunomocniku() {
        return new PodaciOPunomocniku();
    }

    public PodaciOPronalazacu createPodaciOPronalazacu() {
        return new PodaciOPronalazacu();
    }

    public PodaciOPrijavi createPodaciOPrijavi() {
        return new PodaciOPrijavi();
    }

    public PodaciOPodnosiocuPrijave createPodaciOPodnosiocuPrijave() {
        return new PodaciOPodnosiocuPrijave();
    }

    public OsnovneInformacijeOZahtevuZaPriznanjePatenta createOsnovneInformacijeOZahtevuZaPriznanjePatenta() {
        return new OsnovneInformacijeOZahtevuZaPriznanjePatenta();
    }

    public NazivPronalaska createNazivPronalaska() {
        return new NazivPronalaska();
    }

    public Dostavljanje createDostavljanje() {
        return new Dostavljanje();
    }

    public Adresa createAdresa() {
        return new Adresa();
    }
}
