public enum ETip_priloga {
    PRIMERAK_ZNAKA,
    SPISAK_ROBE_I_USLUGA,
    PUNOMOCJE,
    GENERALNO_PUNOMOCJE_RANIJE_PRILOZENO,
    PUNOMOCJE_CE_BITI_NAKNADNO_DOSTAVLJENO,
    OPSTI_AKT_O_ZIGU,
    DOKAZ_O_PRAVU_PRVENSTVA,
    DOKAZ_O_UPLATI_TAKSE
}
