//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.01 at 03:08:59 PM CET 
//


import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

@XmlRegistry
public class ObjectFactory {

    private final static QName _Zahtev_za_zig_QNAME = new QName("http://www.ftn.uns.ac.rs/zig", "zigg");

    public ObjectFactory() {
    }

    public Adresa createAdresa() {
        return new Adresa();
    }

    public FizickoLice createFizickoLice() {
        return new FizickoLice();
    }

    public Klasa createKlasa() {
        return new Klasa();
    }

    public Kontakt createKontakt() {
        return new Kontakt();
    }

    public PravnoLice createPravnoLice() {
        return new PravnoLice();
    }

    public PrilogPunomocje createPrilogPunomocje() {
        return new PrilogPunomocje();
    }

    public Prilog createPrilog() {
        return new Prilog();
    }

    public Taksa createTaksa() {
        return new Taksa();
    }

    public ZahtevZaPriznanjeZiga createZahtevZaPriznanjeZiga() {
        return new ZahtevZaPriznanjeZiga();
    }

    public Zig createZig() {
        return new Zig();
    }

}
